export interface Pianist {
  id : number;
  name : string;
  school? : string;
  birth? : number;
  death? : number;
  infoLink? : string;
  wikiLink? : string;
  imageLink? : string;
  students : number[];
  teachers : number[];
  link? : string;
}

export const UPDATEDPLAYERS : Pianist [] =  [
{"id":116,"name":"Claudio Arrau","school":"","birth":1903,"death":1991,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[27]}, 
{"id":115,"name":"Peter Winter","school":"","birth":1754,"death":1825,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[104]}, 
{"id":114,"name":"Joseph Weigl","school":"","birth":1766,"death":1846,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[104]}, 
{"id":113,"name":"Franz Xaver Süssmayr","school":"","birth":1766,"death":1803,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[104]}, 
{"id":112,"name":"Franz Schubert","school":"","birth":1797,"death":1828,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[104]}, 
{"id":111,"name":"Maria Theresia von Paradis","school":"","birth":1759,"death":1824,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[104]}, 
{"id":110,"name":"Franz Xaver Wolfgang Mozart","school":"","birth":1791,"death":1844,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[104]}, 
{"id":109,"name":"Ignaz Moscheles","school":"","birth":1794,"death":1870,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[104]}, 
{"id":108,"name":"Giacomo Meyerbeer","school":"","birth":1791,"death":1864,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[104]}, 
{"id":107,"name":"Johann Nepomuk Hummel","school":"","birth":1778,"death":1837,"infoLink":"","wikiLink":"","imageLink":"","students":[2,13],"teachers":[104]}, 
{"id":106,"name":"Antonio Casimir Cartellieri","school":"","birth":1772,"death":1807,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[104]}, 
{"id":105,"name":"Marianna Auenbrugger","school":"","birth":1759,"death":1782,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[104]}, 
{"id":104,"name":"Antonio Salieri","school":"","birth":1750,"death":1825,"infoLink":"","wikiLink":"","imageLink":"","students":[1,105,106,2,107,5,108,109,110,111,112,113,114,115],"teachers":[]}, 
{"id":103,"name":"Cecile Staub Genhart","school":"","birth":1899,"death":1983,"infoLink":"","wikiLink":"","imageLink":"","students":[101],"teachers":[]}, 
{"id":102,"name":"Leonard Shure","school":"","birth":1910,"death":1995,"infoLink":"","wikiLink":"","imageLink":"","students":[101],"teachers":[87]}, 
{"id":101,"name":"Richard Becker","school":"","infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[102,103]}, 
{"id":100,"name":"Joseph Haydn","school":"","birth":1732,"death":1809,"infoLink":"","wikiLink":"","imageLink":"","students":[1],"teachers":[]}, 
{"id":99,"name":"Alfonso Rendano","school":"","birth":1853,"death":1931,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[13]}, 
{"id":98,"name":"Charles Poisot","school":"","birth":1822,"death":1904,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[13]}, 
{"id":97,"name":"Anton de Kontski","school":"","birth":1816,"death":1899,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[13]}, 
{"id":96,"name":"Beniamino Cesi","school":"","birth":1845,"death":1907,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[13]}, 
{"id":95,"name":"Charles-Wilfrid de Bériot","school":"","birth":1833,"death":1914,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[13]}, 
{"id":94,"name":"Anna Yesipova","school":"","birth":1851,"death":1914,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":93,"name":"Paul Wittgenstein","school":"","birth":1887,"death":1961,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":92,"name":"Alexander Winkler","school":"","birth":1865,"death":1935,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":91,"name":"Emerson Whithorne","school":"","birth":1884,"death":1958,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":90,"name":"Anastasia Virsaladze","school":"","birth":1883,"death":1968,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":89,"name":"Isabelle Vengerova","school":"","birth":1877,"death":1956,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":88,"name":"Eleanor Spencer","school":"","birth":1890,"death":1973,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":87,"name":"Artur Schnabel","school":"","birth":1882,"death":1951,"infoLink":"","wikiLink":"","imageLink":"","students":[102],"teachers":[11]}, 
{"id":86,"name":"Vasily Safonov","school":"","birth":1852,"death":1918,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":85,"name":"Alexander Raab","school":"","birth":1882,"death":1958,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":84,"name":"Ignacy Jan Paderewski","school":"","birth":1860,"death":1941,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":83,"name":"Marie Novello","school":"","birth":1884,"death":1928,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":82,"name":"Elly Ney","school":"","birth":1882,"death":1968,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":81,"name":"Benno Moiseiwitsch","school":"","birth":1890,"death":1963,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":80,"name":"Franz Mittler","school":"","birth":1893,"death":1970,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":79,"name":"Frank Merrick","school":"","birth":1886,"death":1981,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":78,"name":"Ethel Leginska","school":"","birth":1886,"death":1970,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":77,"name":"Edwin Hughes","school":"","birth":1884,"death":1965,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":76,"name":"Mieczysław Horszowski","school":"","birth":1892,"death":1993,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":75,"name":"Mark Hambourg","school":"","birth":1879,"death":1960,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":74,"name":"Heinrich Gebhard","school":"","birth":1878,"death":1963,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":73,"name":"Ossip Gabrilowitsch","school":"","birth":1878,"death":1936,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":72,"name":"Ignaz Friedman","school":"","birth":1882,"death":1948,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":71,"name":"Jeannette Durno","school":"","birth":1876,"death":1963,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":70,"name":"Richard Buhlig","school":"","birth":1880,"death":1952,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":69,"name":"Alexander Brailowsky","school":"","birth":1896,"death":1976,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[11]}, 
{"id":68,"name":"Fred Werner","school":"","birth":1850,"death":1920,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":67,"name":"Xaver Scharwenka","school":"","birth":1850,"death":1924,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":66,"name":"Nikolai Rubinstein","school":"","birth":1835,"death":1881,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":65,"name":"Julius Reubke","school":"","birth":1834,"death":1858,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":64,"name":"Silas G. Pratt","school":"","birth":1846,"death":1916,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":63,"name":"Rikard Nordraak","school":"","birth":1842,"death":1866,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":62,"name":"Moritz Moszkowski","school":"","birth":1854,"death":1925,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":61,"name":"Leonard Liebling","school":"","birth":1874,"death":1945,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":60,"name":"James Kwast","school":"","birth":1852,"death":1927,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":59,"name":"Alexander Ilyinsky","school":"","birth":1859,"death":1920,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":58,"name":"Heinrich Hofmann","school":"","birth":1842,"death":1902,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":57,"name":"Alfred Grünfeld","school":"","birth":1852,"death":1924,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[10]}, 
{"id":56,"name":"Samuel Sanford","school":"","birth":1849,"death":1910,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[9]}, 
{"id":55,"name":"Benjamin Johnson Lang","school":"","birth":1837,"death":1909,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[9]}, 
{"id":54,"name":"Isidor Philipp","school":"","birth":1863,"death":1958,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[8]}, 
{"id":53,"name":"Alexander von Zemlinsky","school":"","birth":1871,"death":1942,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[7]}, 
{"id":52,"name":"Fritz Steinbach","school":"","birth":1855,"death":1916,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[7]}, 
{"id":51,"name":"Pavel Pabst","school":"","birth":1854,"death":1897,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[7]}, 
{"id":50,"name":"Laura Netzel","school":"","birth":1839,"death":1927,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[7]}, 
{"id":49,"name":"Hans May","school":"","birth":1886,"death":1959,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[7]}, 
{"id":48,"name":"Robert Fischhof","school":"","birth":1856,"death":1918,"infoLink":"","wikiLink":"","imageLink":"","students":[],"teachers":[7]}, 
{"id":47,"name":"Géza Zichy","school":"","birth":1849,"death":1924,"infoLink":"https://en.wikipedia.org/wiki/G%C3%A9za_Zichy","wikiLink":"https://en.wikipedia.org/wiki/G%C3%A9za_Zichy","imageLink":"","students":[],"teachers":[5]}, 
{"id":46,"name":"Józef Wieniawski","school":"","birth":1837,"death":1912,"infoLink":"https://en.wikipedia.org/wiki/J%C3%B3zef_Wieniawski","wikiLink":"https://en.wikipedia.org/wiki/J%C3%B3zef_Wieniawski","imageLink":"","students":[],"teachers":[5]}, 
{"id":45,"name":"José Vianna da Motta","school":"","birth":1868,"death":1948,"infoLink":"https://en.wikipedia.org/wiki/Jos%C3%A9_Vianna_da_Motta","wikiLink":"https://en.wikipedia.org/wiki/Jos%C3%A9_Vianna_da_Motta","imageLink":"","students":[],"teachers":[5]}, 
{"id":44,"name":"Anton Urspruch","school":"","birth":1850,"death":1907,"infoLink":"https://en.wikipedia.org/wiki/Anton_Urspruch","wikiLink":"https://en.wikipedia.org/wiki/Anton_Urspruch","imageLink":"","students":[],"teachers":[5]}, 
{"id":43,"name":"Vera Timanova","school":"","birth":1855,"death":1942,"infoLink":"https://en.wikipedia.org/wiki/Vera_Timanova","wikiLink":"https://en.wikipedia.org/wiki/Vera_Timanova","imageLink":"","students":[],"teachers":[5]}, 
{"id":42,"name":"István Thomán","school":"","birth":1862,"death":1940,"infoLink":"https://en.wikipedia.org/wiki/Istv%C3%A1n_Thom%C3%A1n","wikiLink":"https://en.wikipedia.org/wiki/Istv%C3%A1n_Thom%C3%A1n","imageLink":"","students":[],"teachers":[5]}, 
{"id":41,"name":"Hilda Thegerström","school":"","birth":1838,"death":1907,"infoLink":"https://en.wikipedia.org/wiki/Hilda_Thegerstr%C3%B6m","wikiLink":"https://en.wikipedia.org/wiki/Hilda_Thegerstr%C3%B6m","imageLink":"","students":[],"teachers":[5]}, 
{"id":40,"name":"Bernhard Stavenhagen","school":"","birth":1862,"death":1914,"infoLink":"https://en.wikipedia.org/wiki/Bernhard_Stavenhagen","wikiLink":"https://en.wikipedia.org/wiki/Bernhard_Stavenhagen","imageLink":"","students":[],"teachers":[5]}, 
{"id":39,"name":"Karl Tausig","school":"","birth":1841,"death":1871,"infoLink":"https://en.wikipedia.org/wiki/Karl_Tausig","wikiLink":"https://en.wikipedia.org/wiki/Karl_Tausig","imageLink":"","students":[],"teachers":[5]}, 
{"id":38,"name":"Alexander Siloti","school":"","birth":1963,"death":1945,"infoLink":"https://en.wikipedia.org/wiki/Alexander_Siloti","wikiLink":"https://en.wikipedia.org/wiki/Alexander_Siloti","imageLink":"","students":[],"teachers":[5]}, 
{"id":37,"name":"William Hall Sherwood","school":"","birth":1854,"death":1911,"infoLink":"https://en.wikipedia.org/wiki/William_Hall_Sherwood","wikiLink":"https://en.wikipedia.org/wiki/William_Hall_Sherwood","imageLink":"","students":[],"teachers":[5,10]}, 
{"id":36,"name":"Giovanni Sgambati","school":"","birth":1841,"death":1914,"infoLink":"https://en.wikipedia.org/wiki/Giovanni_Sgambati","wikiLink":"https://en.wikipedia.org/wiki/Giovanni_Sgambati","imageLink":"","students":[],"teachers":[5]}, 
{"id":35,"name":"Emil von Sauer","school":"","birth":1862,"death":1942,"infoLink":"https://en.wikipedia.org/wiki/Emil_von_Sauer","wikiLink":"https://en.wikipedia.org/wiki/Emil_von_Sauer","imageLink":"","students":[],"teachers":[5]}, 
{"id":34,"name":"Moriz Rosenthal","school":"","birth":1862,"death":1946,"infoLink":"https://en.wikipedia.org/wiki/Moriz_Rosenthal","wikiLink":"https://en.wikipedia.org/wiki/Moriz_Rosenthal","imageLink":"","students":[],"teachers":[5]}, 
{"id":33,"name":"Carl Reinecke","school":"","birth":1824,"death":1910,"infoLink":"https://en.wikipedia.org/wiki/Carl_Reinecke","wikiLink":"https://en.wikipedia.org/wiki/Carl_Reinecke","imageLink":"","students":[],"teachers":[5]}, 
{"id":32,"name":"Sebastian Bach Mills","school":"","birth":1839,"death":1898,"infoLink":"https://en.wikipedia.org/wiki/Sebastian_Bach_Mills","wikiLink":"https://en.wikipedia.org/wiki/Sebastian_Bach_Mills","imageLink":"","students":[],"teachers":[5]}, 
{"id":31,"name":"Sophie Menter","school":"","birth":1846,"death":1918,"infoLink":"https://en.wikipedia.org/wiki/Sophie_Menter","wikiLink":"https://en.wikipedia.org/wiki/Sophie_Menter","imageLink":"","students":[],"teachers":[5]}, 
{"id":30,"name":"Max Liebling","school":"","birth":1845,"death":1927,"infoLink":"https://en.wikipedia.org/wiki/Max_Liebling","wikiLink":"https://en.wikipedia.org/wiki/Max_Liebling","imageLink":"","students":[],"teachers":[5]}, 
{"id":29,"name":"Wilhelm von Lenz","school":"","birth":1809,"death":1883,"infoLink":"https://en.wikipedia.org/wiki/Wilhelm_von_Lenz","wikiLink":"https://en.wikipedia.org/wiki/Wilhelm_von_Lenz","imageLink":"","students":[],"teachers":[5]}, 
{"id":28,"name":"Frederic Lamond","school":"","birth":1868,"death":1948,"infoLink":"https://en.wikipedia.org/wiki/Frederic_Lamond_(pianist)","wikiLink":"https://en.wikipedia.org/wiki/Frederic_Lamond_(pianist)","imageLink":"","students":[],"teachers":[5]}, 
{"id":27,"name":"Martin Krause","school":"","birth":1853,"death":1918,"infoLink":"https://en.wikipedia.org/wiki/Martin_Krause","wikiLink":"https://en.wikipedia.org/wiki/Martin_Krause","imageLink":"","students":[116],"teachers":[5]}, 
{"id":26,"name":"Karl Klindworth","school":"","birth":1830,"death":1916,"infoLink":"https://en.wikipedia.org/wiki/Karl_Klindworth","wikiLink":"https://en.wikipedia.org/wiki/Karl_Klindworth","imageLink":"","students":[],"teachers":[5]}, 
{"id":25,"name":"Arthur Friedheim","school":"","birth":1859,"death":1932,"infoLink":"https://en.wikipedia.org/wiki/Arthur_Friedheim","wikiLink":"https://en.wikipedia.org/wiki/Arthur_Friedheim","imageLink":"","students":[],"teachers":[5]}, 
{"id":24,"name":"Amy Fay","school":"","birth":1844,"death":1928,"infoLink":"https://en.wikipedia.org/wiki/Amy_Fay","wikiLink":"https://en.wikipedia.org/wiki/Amy_Fay","imageLink":"","students":[],"teachers":[5,10]}, 
{"id":23,"name":"Arthur De Greef","school":"","birth":1862,"death":1940,"infoLink":"https://en.wikipedia.org/wiki/Arthur_De_Greef_(composer)","wikiLink":"https://en.wikipedia.org/wiki/Arthur_De_Greef_(composer)","imageLink":"","students":[],"teachers":[5]}, 
{"id":22,"name":"Hans von Bülow","school":"","birth":1830,"death":1894,"infoLink":"https://en.wikipedia.org/wiki/Hans_von_B%C3%BClow","wikiLink":"https://en.wikipedia.org/wiki/Hans_von_B%C3%BClow","imageLink":"","students":[],"teachers":[5]}, 
{"id":21,"name":"Hans Bronsart von Schellendorff","school":"","birth":1830,"death":1913,"infoLink":"https://en.wikipedia.org/wiki/Hans_Bronsart_von_Schellendorff","wikiLink":"https://en.wikipedia.org/wiki/Hans_Bronsart_von_Schellendorff","imageLink":"","students":[],"teachers":[5]}, 
{"id":20,"name":"Arthur H. Bird","school":"","birth":1856,"death":1923,"infoLink":"https://en.wikipedia.org/wiki/Arthur_H._Bird","wikiLink":"https://en.wikipedia.org/wiki/Arthur_H._Bird","imageLink":"","students":[],"teachers":[5]}, 
{"id":19,"name":"Carl Baermann","school":"","birth":1810,"death":1885,"infoLink":"https://en.wikipedia.org/wiki/Carl_Baermann#Carl_Baermann_(son)","wikiLink":"https://en.wikipedia.org/wiki/Carl_Baermann#Carl_Baermann_(son)","imageLink":"","students":[],"teachers":[5]}, 
{"id":18,"name":"Agathe Backer Grøndahl","school":"","birth":1847,"death":1907,"infoLink":"https://en.wikipedia.org/wiki/Agathe_Backer_Gr%C3%B8ndahl","wikiLink":"https://en.wikipedia.org/wiki/Agathe_Backer_Gr%C3%B8ndahl","imageLink":"","students":[],"teachers":[5,10]}, 
{"id":17,"name":"Mikhail Azanchevsky","school":"","birth":1839,"death":1881,"infoLink":"https://en.wikipedia.org/wiki/Mikhail_Azanchevsky","wikiLink":"https://en.wikipedia.org/wiki/Mikhail_Azanchevsky","imageLink":"","students":[],"teachers":[5]}, 
{"id":16,"name":"Conrad Ansorge","school":"","birth":1862,"death":1930,"infoLink":"https://en.wikipedia.org/wiki/Conrad_Ansorge","wikiLink":"https://en.wikipedia.org/wiki/Conrad_Ansorge","imageLink":"","students":[],"teachers":[5]}, 
{"id":15,"name":"Eugen d'Albert","school":"","birth":1864,"death":1932,"infoLink":"https://en.wikipedia.org/wiki/Eugen_d%27Albert","wikiLink":"https://en.wikipedia.org/wiki/Eugen_d%27Albert","imageLink":"","students":[],"teachers":[5]}, 
{"id":14,"name":"Károly Aggházy","school":"","birth":1855,"death":1918,"infoLink":"https://en.wikipedia.org/wiki/K%C3%A1roly_Aggh%C3%A1zy","wikiLink":"https://en.wikipedia.org/wiki/K%C3%A1roly_Aggh%C3%A1zy","imageLink":"","students":[],"teachers":[5]}, 
{"id":13,"name":"Sigismond Thalberg","school":"","birth":1812,"death":1871,"infoLink":"https://en.wikipedia.org/wiki/Sigismond_Thalberg","wikiLink":"https://en.wikipedia.org/wiki/Sigismond_Thalberg","imageLink":"","students":[95,96,97,98,99],"teachers":[2,107]}, 
{"id":12,"name":"Anna Caroline Oury","school":"","birth":1806,"death":1880,"infoLink":"https://en.wikipedia.org/wiki/Anna_Caroline_Oury","wikiLink":"https://en.wikipedia.org/wiki/Anna_Caroline_Oury","imageLink":"","students":[],"teachers":[2]}, 
{"id":11,"name":"Theodor Leschetizky","school":"","birth":1830,"death":1915,"infoLink":"https://en.wikipedia.org/wiki/Theodor_Leschetizky","wikiLink":"https://en.wikipedia.org/wiki/Theodor_Leschetizky","imageLink":"","students":[69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94],"teachers":[2]}, 
{"id":10,"name":"Theodor Kullak","school":"","birth":1818,"death":1882,"infoLink":"https://en.wikipedia.org/wiki/Theodor_Kullak","wikiLink":"https://en.wikipedia.org/wiki/Theodor_Kullak","imageLink":"","students":[18,24,57,58,59,60,61,62,63,64,65,66,67,37,68],"teachers":[2]}, 
{"id":9,"name":"Alfred Jaëll","school":"","birth":1832,"death":1882,"infoLink":"https://en.wikipedia.org/wiki/Alfred_Ja%C3%ABll","wikiLink":"https://en.wikipedia.org/wiki/Alfred_Ja%C3%ABll","imageLink":"","students":[55,56],"teachers":[2]}, 
{"id":8,"name":"Stephen Heller","school":"","birth":1813,"death":1888,"infoLink":"https://en.wikipedia.org/wiki/Stephen_Heller","wikiLink":"https://en.wikipedia.org/wiki/Stephen_Heller","imageLink":"","students":[54],"teachers":[2]}, 
{"id":7,"name":"Anton Door","school":"","birth":1833,"death":1919,"infoLink":"https://en.wikipedia.org/wiki/Anton_Door","wikiLink":"https://en.wikipedia.org/wiki/Anton_Door","imageLink":"","students":[48,49,50,51,52,53],"teachers":[2]}, 
{"id":6,"name":"Karl van Beethoven","school":"","birth":1806,"death":1858,"infoLink":"https://en.wikipedia.org/wiki/Karl_van_Beethoven","wikiLink":"https://en.wikipedia.org/wiki/Karl_van_Beethoven","imageLink":"","students":[],"teachers":[2]}, 
{"id":5,"name":"Franz Liszt","school":"","birth":1811,"death":1886,"infoLink":"https://en.wikipedia.org/wiki/Franz_Liszt","wikiLink":"https://en.wikipedia.org/wiki/Franz_Liszt","imageLink":"","students":[14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47],"teachers":[2,104]}, 
{"id":4,"name":"Ferdinand Ries","school":"","birth":1784,"death":1838,"infoLink":"https://en.wikipedia.org/wiki/Ferdinand_Ries","wikiLink":"https://en.wikipedia.org/wiki/Ferdinand_Ries","imageLink":"","students":[],"teachers":[1]}, 
{"id":3,"name":"Dorothea von Ertmann","school":"","birth":1781,"death":1849,"infoLink":"https://en.wikipedia.org/wiki/Dorothea_von_Ertmann","wikiLink":"https://en.wikipedia.org/wiki/Dorothea_von_Ertmann","imageLink":"","students":[],"teachers":[1]}, 
{"id":2,"name":"Carl Czerny","school":"","birth":1791,"death":1857,"infoLink":"https://en.wikipedia.org/wiki/Carl_Czerny","wikiLink":"https://en.wikipedia.org/wiki/Carl_Czerny","imageLink":"","students":[5,6,7,8,9,10,11,12,13],"teachers":[1,104,107]}, 
{"id":1,"name":"Ludwig van Beethoven","school":"","birth":1770,"death":1827,"infoLink":"https://en.wikipedia.org/wiki/Ludwig_van_Beethoven","wikiLink":"https://en.wikipedia.org/wiki/Ludwig_van_Beethoven","imageLink":"","students":[2,3,4],"teachers":[100,104]}];
